language: node_js
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
node_js:
  - 8.90
after_success:
  - docker build -t $DOCKER_IMAGE --build-arg azure_user="$AZURE_WA_USERNAME"  --build-arg azure_pwd="$AZURE_WA_PASSWORD"  --build-arg azure_site="$AZURE_WA_SITE" .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE
  - docker logout
