language: node_js
sudo: required
services:
  - docker
node_js:
  - 8.90
after_success:
  - npm run build
#  - docker build . -t tklepzig/sketchbook
#  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
#  - docker push tklepzig/sketchbook
before_deploy:
  - git add -f dist
  - rm -rf node_modules
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
