language: node_js
sudo: required
services:
  - docker
node_js:
  - 8.90
before_install:
  - docker login -u '$DOCKER_USERNAME' -p '$DOCKER_PASSWORD'
after_success:
  - npm run build
  - docker build . -t tklepzig/sketchbook
  - docker push tklepzig/sketchbook
  - docker logout
before_deploy:
  - git add -f dist
  - rm -rf node_modules
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
